name: 11ty build and deploy
on:
  push:
    branches:
      - 'main'

jobs:

  build_deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run eleventy build
        uses: maschmann/eleventy-build-action@main
        with:
          node_version: 23  # default
          output: './_site' # default
          quiet: true       # default false

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_NAME }}
          username: ${{ secrets.SERVER_DEPLOY_USER }}
          key: ${{ secrets.SERVER_DEPLOY_KEY }}
          rm: true
          source: "_site/"
          target: ${{ vars.DEPLOYMENT_TARGET }}
